services:
  flaskcontact:
    container_name: flaskcontact
    image: tunaa/flaskwebapp:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:simonza01@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simonza01
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
